## 0. Entorno y carga de ficheros

In [1]:
import pandas as pd
import openpyxl
import numpy as np
import seaborn as sns
import matplotlib as plt
import plotly.express as px
import plotly.io as pio
from pathlib import Path

In [2]:
#Carga CSV 'FAOSTAT'
agric_ONU = pd.read_csv('/Users/rosamariasierraalmeria/Documents/GitHub/Impacto-del-clima-en-la-agricultura-/data/FAOSTAT_data_es_6-11-2026.csv')

In [3]:
#Carga CSV 'NASA'
#skiprows= elimna las 13 primeras filas, que no son necesarias
#na_values=['-999', '-999.0'] convierte valor -999 y -999.0 en NA
clima_NASA = pd.read_csv(
    '/Users/rosamariasierraalmeria/Documents/GitHub/Impacto-del-clima-en-la-agricultura-/data/POWER_Point_Monthly_20050101_20241231_040d42N_003d70W_LST.csv',
    skiprows=13,
    na_values=['-999', '-999.0']
)

In [4]:
#Carga de CSV 'ESYRCE'
#header=4 para llegar al encabezado que me interesa.
agric_ESP = pd.read_excel('/Users/rosamariasierraalmeria/Documents/GitHub/Impacto-del-clima-en-la-agricultura-/data/Dinaweb2024-2.xlsx', header=4)

In [36]:
#Carga de CSV 'tabla final AEMET'
clima_AEMET = pd.read_csv('/Users/rosamariasierraalmeria/Documents/GitHub/Impacto-del-clima-en-la-agricultura-/data/AEMET/tablas_limpias/aemet_final.csv')

---
## 1. Limpieza dataset.

In [6]:
#Gestión de nulos 'FAOSTAT'
agric_ONU.info()

<class 'pandas.DataFrame'>
RangeIndex: 5904 entries, 0 to 5903
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Código del ámbito          5904 non-null   str
 1   Ámbito                     5904 non-null   str
 2   Código del área (M49)      5904 non-null   int64
 3   Área                       5904 non-null   str
 4   Código del elemento        5904 non-null   int64
 5   Elemento                   5904 non-null   str
 6   Código del producto (CPC)  5904 non-null   str
 7   Producto                   5904 non-null   str
 8   Código del año             5904 non-null   int64
 9   Año                        5904 non-null   int64
 10  Unidad                     5904 non-null   str
 11  Valor                      5823 non-null   float64
 12  Símbolo                    5904 non-null   str
 13  Descripción del Símbolo    5904 non-null   str
 14  Nota                       210 non-null    str
dtypes: float64(1), int64(4), str(10)
memory usage: 692.0 KB

In [7]:
#Total nulos 'FAOSTAT'
agric_ONU.isnull().sum()

Código del ámbito               0
Ámbito                          0
Código del área (M49)           0
Área                            0
Código del elemento             0
Elemento                        0
Código del producto (CPC)       0
Producto                        0
Código del año                  0
Año                             0
Unidad                          0
Valor                          81
Símbolo                         0
Descripción del Símbolo         0
Nota                         5694
dtype: int64

In [8]:
#Porcentaje de nulos 'FAOSTAT'
(agric_ONU.isnull().sum() / len(agric_ONU)) * 100

Código del ámbito             0.000000
Ámbito                        0.000000
Código del área (M49)         0.000000
Área                          0.000000
Código del elemento           0.000000
Elemento                      0.000000
Código del producto (CPC)     0.000000
Producto                      0.000000
Código del año                0.000000
Año                           0.000000
Unidad                        0.000000
Valor                         1.371951
Símbolo                       0.000000
Descripción del Símbolo       0.000000
Nota                         96.443089
dtype: float64

In [9]:
agric_ONU[agric_ONU["Valor"].isna()]["Producto"].value_counts()

Producto
Kenaf y otras fibras textiles de líber, brutas o enriadas    27
Grosellas                                                    14
Pelitre, flores secas                                        14
Café, verde                                                  13
Algarrobas                                                   12
Lino, en rama o enriado                                       1
Name: count, dtype: int64

Dataset con muy poco porcentaje de nulos, no merece la pena hacer modificaciones.

In [10]:
#Revisión de valores duplicados 'FAOSTAT'.
agric_ONU.duplicated().sum()

np.int64(0)

In [11]:
#Consultas de varias columnas para revisar el contenido y decidir si me las elimino o no.
agric_ONU["Símbolo"].value_counts(dropna=False)

Símbolo
A    4849
E     498
I     244
X     232
M      81
Name: count, dtype: int64

In [12]:
agric_ONU.groupby(
    ["Símbolo", "Descripción del Símbolo"]
).size()

Símbolo  Descripción del Símbolo
A        Cifra oficial                                 4849
E        Valor estimado                                 498
I        Valor imputado por una agencia receptora       244
M        Valor ausente; los datos no pueden existir      81
X        Cifra de fuente externa                        232
dtype: int64

In [13]:
#Gestión de nulos 'ESYRCE'
agric_ESP.info()

<class 'pandas.DataFrame'>
RangeIndex: 5494 entries, 0 to 5493
Data columns (total 22 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Cultivos y cubiertas de suelo  5494 non-null   str
 1   2004                           3434 non-null   float64
 2   2005                           3417 non-null   float64
 3   2006                           3433 non-null   float64
 4   2007                           3484 non-null   float64
 5   2008                           3434 non-null   float64
 6   2009                           3527 non-null   float64
 7   2010                           3607 non-null   float64
 8   2011                           3609 non-null   float64
 9   2012                           3592 non-null   float64
 10  2013                           3661 non-null   float64
 11  2014                           3648 non-null   float64
 12  2015                           3711 non-null   float64
 13  2016                           3716 non-null   float64
 14  2017                           3773 non-null   float64
 15  2018                           3792 non-null   float64
 16  2019                           3808 non-null   float64
 17  2020                           3757 non-null   float64
 18  2021                           3736 non-null   float64
 19  2022                           3827 non-null   float64
 20  2023                           3843 non-null   float64
 21  2024                           3841 non-null   float64
dtypes: float64(21), str(1)
memory usage: 944.4 KB

In [14]:
#Total nulos 'ESYRCE'
agric_ESP.isnull().sum()

Cultivos y cubiertas de suelo       0
2004                             2060
2005                             2077
2006                             2061
2007                             2010
2008                             2060
2009                             1967
2010                             1887
2011                             1885
2012                             1902
2013                             1833
2014                             1846
2015                             1783
2016                             1778
2017                             1721
2018                             1702
2019                             1686
2020                             1737
2021                             1758
2022                             1667
2023                             1651
2024                             1653
dtype: int64

In [15]:
#Porcentaje de nulos 'ESYRCE'
(agric_ESP.isnull().sum() / len(agric_ESP)) * 100

Cultivos y cubiertas de suelo     0.000000
2004                             37.495450
2005                             37.804878
2006                             37.513651
2007                             36.585366
2008                             37.495450
2009                             35.802694
2010                             34.346560
2011                             34.310157
2012                             34.619585
2013                             33.363669
2014                             33.600291
2015                             32.453586
2016                             32.362577
2017                             31.325082
2018                             30.979250
2019                             30.688023
2020                             31.616309
2021                             31.998544
2022                             30.342191
2023                             30.050965
2024                             30.087368
dtype: float64

In [17]:
#Revisión de valores duplicados 'ESYRCE'.
agric_ESP.duplicated().sum()

np.int64(3)

In [18]:
agric_ESP.isnull().all(axis=1).sum()

np.int64(0)

In [19]:
agric_ESP["Cultivos y cubiertas de suelo"].isnull().sum()

np.int64(0)

In [20]:
agric_ESP["Cultivos y cubiertas de suelo"].duplicated().sum()

np.int64(5262)

In [22]:
#Revisión de valores duplicados 'NASA'.
clima_NASA.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PARAMETER  100 non-null    str
 1   YEAR       100 non-null    int64
 2   JAN        100 non-null    float64
 3   FEB        100 non-null    float64
 4   MAR        100 non-null    float64
 5   APR        100 non-null    float64
 6   MAY        100 non-null    float64
 7   JUN        100 non-null    float64
 8   JUL        100 non-null    float64
 9   AUG        100 non-null    float64
 10  SEP        100 non-null    float64
 11  OCT        100 non-null    float64
 12  NOV        100 non-null    float64
 13  DEC        100 non-null    float64
 14  ANN        100 non-null    float64
dtypes: float64(13), int64(1), str(1)
memory usage: 11.8 KB

In [24]:
#Revisión de valores duplicados 'ESYRCE'.
clima_NASA.duplicated().sum()

np.int64(0)

In [37]:
#Revisión de valores duplicados 'AEMET'.
clima_AEMET.info()

<class 'pandas.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   anio           84 non-null     int64
 1   temp_media     84 non-null     float64
 2   temp_min       84 non-null     float64
 3   temp_max       84 non-null     float64
 4   precipitacion  84 non-null     float64
 5   provincia      84 non-null     str
dtypes: float64(4), int64(1), str(1)
memory usage: 4.1 KB

In [40]:
clima_NASA.duplicated().sum()

np.int64(0)

In [43]:
#Creación de copias para comenzar a eliminar las columnas que no son necesarias.
agric_ONU_copia = agric_ONU.copy()

In [44]:
agric_ESP_copia = agric_ESP.copy()

In [45]:
clima_NASA_copia = clima_NASA.copy()

In [46]:
clima_AEMET_copia = clima_AEMET.copy()

In [ ]:
#Revisión de columnas FAOSTAT
agric_ONU_copia.head()

,Código del ámbito,Ámbito,Código del área (M49),Área,Código del elemento,Elemento,Código del producto (CPC),Producto,Código del año,Año,Unidad,Valor,Símbolo,Descripción del Símbolo,Nota
0,QCL,Cultivos y productos de ganadería,724,España,5510,Producción,21641.01,"Aceite de colza, en bruto",2005,2005,toneladas,6300.0,X,Cifra de fuente externa,Cifras no oficiales
1,QCL,Cultivos y productos de ganadería,724,España,5510,Producción,21641.01,"Aceite de colza, en bruto",2006,2006,toneladas,34300.0,X,Cifra de fuente externa,Cifras no oficiales
2,QCL,Cultivos y productos de ganadería,724,España,5510,Producción,21641.01,"Aceite de colza, en bruto",2007,2007,toneladas,28700.0,X,Cifra de fuente externa,Cifras no oficiales
3,QCL,Cultivos y productos de ganadería,724,España,5510,Producción,21641.01,"Aceite de colza, en bruto",2008,2008,toneladas,37300.0,X,Cifra de fuente externa,Cifras no oficiales
4,QCL,Cultivos y productos de ganadería,724,España,5510,Producción,21641.01,"Aceite de colza, en bruto",2009,2009,toneladas,42600.0,X,Cifra de fuente externa,Cifras no oficiales

In [ ]:
#Conservación de las columnas Area, Elemento, Producción, Año, Unidad, Valor, Simbolo y Descripción del Símbolo, y elimino las demás.
agric_ONU_final = agric_ONU_copia.drop(columns=['Código del ámbito','Ámbito', 'Código del área (M49)', 'Código del elemento', 'Código del producto (CPC)', 'Código del año', 'Nota'] )

In [58]:
#Creación de índice
agric_ONU_final.index.name = 'Agric_ONU_ID'

In [59]:
agric_ONU_final.head()

,Área,Elemento,Producto,Año,Unidad,Valor,Símbolo,Descripción del Símbolo
Agric_ONU_ID,,,,,,,,
0,España,Producción,"Aceite de colza, en bruto",2005,toneladas,6300.0,X,Cifra de fuente externa
1,España,Producción,"Aceite de colza, en bruto",2006,toneladas,34300.0,X,Cifra de fuente externa
2,España,Producción,"Aceite de colza, en bruto",2007,toneladas,28700.0,X,Cifra de fuente externa
3,España,Producción,"Aceite de colza, en bruto",2008,toneladas,37300.0,X,Cifra de fuente externa
4,España,Producción,"Aceite de colza, en bruto",2009,toneladas,42600.0,X,Cifra de fuente externa

In [91]:
#Revisión de columnas ESYRCE
agric_ESP_copia.head()

,Cultivos y cubiertas de suelo,2004,2005,2006,2007,2008,2009,2010,2011,2012,...,2020,2021,2022,2023,2024,codigo,nombre,tipo,Categoria,Cultivo
Agric_ESP_ID,,,,,,,,,,,,,,,,,,,,,
0,01 Cereales grano,6.578686e+06,6.841004e+06,6.559612e+06,6.372098e+06,6.932676e+06,6.209489e+06,6.126669e+06,6.147707e+06,6.385886e+06,...,6.062895e+06,6.170885e+06,5.946066e+06,5.708288e+06,5.521496e+06,01,Cereales grano,categoria,Cereales grano,
1,01010 TRIGO DURO,9.573725e+05,1.030479e+06,7.550489e+05,5.702965e+05,6.531898e+05,5.849113e+05,5.883079e+05,4.564000e+05,5.356056e+05,...,3.332483e+05,3.304297e+05,3.749712e+05,3.289970e+05,3.086289e+05,01010,TRIGO DURO,cultivo,Cereales grano,TRIGO DURO
2,0115 CORUÑA (LA),4.169314e+02,9.147639e+02,1.962455e+02,8.208600e+00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0115,CORUÑA (LA),provincia,Cereales grano,TRIGO DURO
3,0127 LUGO,1.132357e+02,NaN,3.977237e+02,5.802053e+02,NaN,NaN,NaN,NaN,NaN,...,NaN,1.532132e+02,3.526470e+01,3.526470e+01,3.526470e+01,0127,LUGO,provincia,Cereales grano,TRIGO DURO
4,0132 ORENSE,NaN,1.729853e+02,4.468761e+02,5.723210e+01,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.800710e+01,NaN,0132,ORENSE,provincia,Cereales grano,TRIGO DURO

In [ ]:
#No elimino ninguna columna.

#Saco las columnas Provincia, Categoría y Cultivo
col = agric_ESP_copia.columns[0]  #guarda el nombre de la columna principal

agric_ESP_copia["codigo"] = agric_ESP_copia[col].str.split().str[0]   # extrae la primera palabra (el código)
agric_ESP_copia["nombre"] = agric_ESP_copia[col].str.split(" ", n=1).str[1]  # extrae todo lo que viene después

agric_ESP_copia[["codigo", "nombre"]].head(10)

             codigo          nombre
Agric_ESP_ID
0                01  Cereales grano
1             01010      TRIGO DURO
2              0115     CORUÑA (LA)
3              0127            LUGO
4              0132          ORENSE
5              0136      PONTEVEDRA
6              0233   P,DE ASTURIAS
7              0401           ALAVA
8              0531         NAVARRA
9              0626        LA RIOJA

In [93]:
agric_ESP_copia["tipo"] = agric_ESP_copia["codigo"].str.len().map({
    2: "categoria",
    5: "cultivo",
    4: "provincia"
})

agric_ESP_copia[["codigo", "nombre", "tipo"]].head(10)

             codigo          nombre       tipo
Agric_ESP_ID
0                01  Cereales grano  categoria
1             01010      TRIGO DURO    cultivo
2              0115     CORUÑA (LA)  provincia
3              0127            LUGO  provincia
4              0132          ORENSE  provincia
5              0136      PONTEVEDRA  provincia
6              0233   P,DE ASTURIAS  provincia
7              0401           ALAVA  provincia
8              0531         NAVARRA  provincia
9              0626        LA RIOJA  provincia

In [94]:
categoria_actual = ""
cultivo_actual = ""

categorias = []
cultivos = []

for _, fila in agric_ESP_copia.iterrows():
    if fila["tipo"] == "categoria":
        categoria_actual = fila["nombre"]
        cultivo_actual = ""
    elif fila["tipo"] == "cultivo":
        cultivo_actual = fila["nombre"]
    
    categorias.append(categoria_actual)
    cultivos.append(cultivo_actual)

agric_ESP_copia["Categoria"] = categorias
agric_ESP_copia["Cultivo"] = cultivos

In [95]:
agric_ESP_copia[["tipo", "Categoria", "Cultivo", "nombre"]].head(15)

                   tipo       Categoria     Cultivo          nombre
Agric_ESP_ID
0             categoria  Cereales grano              Cereales grano
1               cultivo  Cereales grano  TRIGO DURO      TRIGO DURO
2             provincia  Cereales grano  TRIGO DURO     CORUÑA (LA)
3             provincia  Cereales grano  TRIGO DURO            LUGO
4             provincia  Cereales grano  TRIGO DURO          ORENSE
5             provincia  Cereales grano  TRIGO DURO      PONTEVEDRA
6             provincia  Cereales grano  TRIGO DURO   P,DE ASTURIAS
7             provincia  Cereales grano  TRIGO DURO           ALAVA
8             provincia  Cereales grano  TRIGO DURO         NAVARRA
9             provincia  Cereales grano  TRIGO DURO        LA RIOJA
10            provincia  Cereales grano  TRIGO DURO          HUESCA
11            provincia  Cereales grano  TRIGO DURO          TERUEL
12            provincia  Cereales grano  TRIGO DURO        ZARAGOZA
13            provincia  Cereales grano  TRIGO DURO       BARCELONA
14            provincia  Cereales grano  TRIGO DURO          GIRONA

In [97]:
agric_ESP_final = agric_ESP_copia[agric_ESP_copia["tipo"] == "provincia"].copy()
agric_ESP_final = agric_ESP_final.rename(columns={"nombre": "Provincia"})

agric_ESP_final[["Categoria", "Cultivo", "Provincia"]].head(10)

                   Categoria     Cultivo      Provincia
Agric_ESP_ID
2             Cereales grano  TRIGO DURO    CORUÑA (LA)
3             Cereales grano  TRIGO DURO           LUGO
4             Cereales grano  TRIGO DURO         ORENSE
5             Cereales grano  TRIGO DURO     PONTEVEDRA
6             Cereales grano  TRIGO DURO  P,DE ASTURIAS
7             Cereales grano  TRIGO DURO          ALAVA
8             Cereales grano  TRIGO DURO        NAVARRA
9             Cereales grano  TRIGO DURO       LA RIOJA
10            Cereales grano  TRIGO DURO         HUESCA
11            Cereales grano  TRIGO DURO         TERUEL

In [98]:
agric_ESP_final.head()

,Cultivos y cubiertas de suelo,2004,2005,2006,2007,2008,2009,2010,2011,2012,...,2020,2021,2022,2023,2024,codigo,Provincia,tipo,Categoria,Cultivo
Agric_ESP_ID,,,,,,,,,,,,,,,,,,,,,
2,0115 CORUÑA (LA),416.9314,914.7639,196.2455,8.2086,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0115,CORUÑA (LA),provincia,Cereales grano,TRIGO DURO
3,0127 LUGO,113.2357,NaN,397.7237,580.2053,NaN,NaN,NaN,NaN,NaN,...,NaN,153.2132,35.2647,35.2647,35.2647,0127,LUGO,provincia,Cereales grano,TRIGO DURO
4,0132 ORENSE,NaN,172.9853,446.8761,57.2321,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,38.0071,NaN,0132,ORENSE,provincia,Cereales grano,TRIGO DURO
5,0136 PONTEVEDRA,95.2970,95.2970,24.2977,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0136,PONTEVEDRA,provincia,Cereales grano,TRIGO DURO
6,"0233 P,DE ASTURIAS",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.3654,NaN,NaN,NaN,NaN,0233,"P,DE ASTURIAS",provincia,Cereales grano,TRIGO DURO

In [ ]:
year_cols = [c for c in agric_ESP_final.columns if str(c).isdigit()]
agric_ESP_final = agric_ESP_final[["Categoria", "Cultivo", "Provincia"] + year_cols]

agric_ESP_final.head(5)

,Categoria,Cultivo,Provincia,2004,2005,2006,2007,2008,2009,2010,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
Agric_ESP_ID,,,,,,,,,,,,,,,,,,,,,
2,Cereales grano,TRIGO DURO,CORUÑA (LA),416.9314,914.7639,196.2455,8.2086,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Cereales grano,TRIGO DURO,LUGO,113.2357,NaN,397.7237,580.2053,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,153.2132,35.2647,35.2647,35.2647
4,Cereales grano,TRIGO DURO,ORENSE,NaN,172.9853,446.8761,57.2321,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0071,NaN
5,Cereales grano,TRIGO DURO,PONTEVEDRA,95.2970,95.2970,24.2977,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Cereales grano,TRIGO DURO,"P,DE ASTURIAS",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,32.3654,NaN,NaN,NaN,NaN

In [100]:
#Añado el indice
agric_ESP_final.index.any = 'Agric_ESP_ID'

In [108]:
#Convierto los años en columnas por si facilita la creación de la tabla en SQL
year_cols = [c for c in agric_ESP_final.columns if str(c).isdigit()]

agric_ESP_final = agric_ESP_final.melt(
    id_vars=["Categoria", "Cultivo", "Provincia"],
    value_vars=year_cols,
    var_name="Año",
    value_name="Hectareas"
)

agric_ESP_final.head(10)

        Categoria     Cultivo      Provincia   Año   Hectareas
0  Cereales grano  TRIGO DURO    CORUÑA (LA)  2004    416.9314
1  Cereales grano  TRIGO DURO           LUGO  2004    113.2357
2  Cereales grano  TRIGO DURO         ORENSE  2004         NaN
3  Cereales grano  TRIGO DURO     PONTEVEDRA  2004     95.2970
4  Cereales grano  TRIGO DURO  P,DE ASTURIAS  2004         NaN
5  Cereales grano  TRIGO DURO          ALAVA  2004         NaN
6  Cereales grano  TRIGO DURO        NAVARRA  2004  15969.1647
7  Cereales grano  TRIGO DURO       LA RIOJA  2004     22.8576
8  Cereales grano  TRIGO DURO         HUESCA  2004   5350.6048
9  Cereales grano  TRIGO DURO         TERUEL  2004    952.5821

In [69]:
#Revisión de columnas NASA
clima_NASA_copia.head()

,PARAMETER,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
Clima_NASA_ID,,,,,,,,,,,,,,,
0,PRECTOTCORR,2005,0.08,1.34,0.60,0.84,0.62,0.73,0.01,0.18,0.28,3.19,1.89,1.09,0.90
1,PRECTOTCORR,2006,1.00,1.61,1.33,1.04,0.65,1.21,0.10,0.35,0.75,3.48,3.59,0.95,1.33
2,PRECTOTCORR,2007,0.64,1.77,0.81,2.56,3.00,1.29,0.04,0.46,0.40,1.60,1.17,0.51,1.18
3,PRECTOTCORR,2008,0.86,1.00,0.47,2.52,3.22,1.29,0.38,0.03,1.27,3.73,0.64,1.83,1.44
4,PRECTOTCORR,2009,1.57,1.52,0.70,1.13,0.79,0.54,0.01,0.19,0.39,1.28,0.73,3.34,1.02

In [66]:
#No elimino ninguna columna.
#Añado el índice
clima_NASA_final = clima_NASA_copia

In [67]:
clima_NASA_final.index.name = 'Clima_NASA_ID'

In [114]:
#Convierto las filas de meses en una columna
clima_NASA_final["PARAMETER"].unique()

<StringArray>
['PRECTOTCORR', 'RH2M', 'T2M', 'T2M_MAX', 'T2M_MIN']
Length: 5, dtype: str

In [115]:
clima_NASA_final = clima_NASA_final[["PARAMETER", "YEAR", "ANN"]].pivot(
    index="YEAR",
    columns="PARAMETER",
    values="ANN"
).reset_index()

clima_NASA_final.columns.name = None  # elimina el nombre "PARAMETER" de las columnas

clima_NASA_final.head(5)

   YEAR  PRECTOTCORR   RH2M    T2M  T2M_MAX  T2M_MIN
0  2005         0.90  58.25  13.34    39.85    -8.90
1  2006         1.33  62.97  13.91    38.00    -5.83
2  2007         1.18  65.07  12.61    38.82    -6.04
3  2008         1.44  64.42  12.79    38.23    -4.36
4  2009         1.02  60.31  13.88    37.81    -6.54

In [68]:
#Revisión de columnas AEMET
clima_AEMET_copia.head()

   anio  temp_media  temp_min   temp_max  precipitacion   provincia
0  2004   12.582787  6.797814  18.371858          323.2  Valladolid
1  2005   12.833699  6.624384  19.038904          275.8  Valladolid
2  2006   13.503836  7.621918  19.383014          522.1  Valladolid
3  2007   12.259178  6.393699  18.125205          495.6  Valladolid
4  2008   12.205738  6.364208  18.048907          546.2  Valladolid

In [70]:
clima_AEMET_final = clima_AEMET_copia

In [71]:
clima_AEMET_final.index.name = 'Clima_AEMET_ID'

In [72]:
clima_AEMET_final.head()

,anio,temp_media,temp_min,temp_max,precipitacion,provincia
Clima_AEMET_ID,,,,,,
0,2004,12.582787,6.797814,18.371858,323.2,Valladolid
1,2005,12.833699,6.624384,19.038904,275.8,Valladolid
2,2006,13.503836,7.621918,19.383014,522.1,Valladolid
3,2007,12.259178,6.393699,18.125205,495.6,Valladolid
4,2008,12.205738,6.364208,18.048907,546.2,Valladolid

In [ ]:
#Exporto CSVs
agric_ONU_final_process = agric_ONU_final.to_csv('/Users/rosamariasierraalmeria/Documents/GitHub/Impacto-del-clima-en-la-agricultura-/DF_procesados/FAOSTAT_procesado.csv')

In [110]:
agric_ESP_final_process = agric_ESP_final.to_csv('/Users/rosamariasierraalmeria/Documents/GitHub/Impacto-del-clima-en-la-agricultura-/DF_procesados/ESYRCE_procesado.csv')

In [116]:
clima_NASA_final_process = clima_NASA_final.to_csv('/Users/rosamariasierraalmeria/Documents/GitHub/Impacto-del-clima-en-la-agricultura-/DF_procesados/NASA_procesado.csv')

In [112]:
clima_AEMET_final_process = clima_AEMET_final.to_csv('/Users/rosamariasierraalmeria/Documents/GitHub/Impacto-del-clima-en-la-agricultura-/DF_procesados/AEMET_procesado.csv')